import type { LLMChatResult, LLMMessage, LLMProvider } from './types';

// ------------------------------------------------------------
// Provider abstraction. AI vendors are swappable via env vars:
//   AI_PROVIDER = demo | openai | openrouter | groq | ollama | custom
// Any OpenAI-compatible /chat/completions endpoint works.
// ------------------------------------------------------------

type ProviderName = 'demo' | 'openai' | 'openrouter' | 'groq' | 'ollama' | 'custom';

const PRESETS: Record<Exclude<ProviderName, 'demo'>, { baseUrl: string; model: string }> = {
  openai: { baseUrl: 'https://api.openai.com/v1', model: 'gpt-4o-mini' },
  openrouter: { baseUrl: 'https://openrouter.ai/api/v1', model: 'openai/gpt-4o-mini' },
  groq: { baseUrl: 'https://api.groq.com/openai/v1', model: 'llama-3.3-70b-versatile' },
  ollama: { baseUrl: 'http://localhost:11434/v1', model: 'llama3.2' },
  custom: { baseUrl: '', model: '' },
};

class OpenAICompatibleProvider implements LLMProvider {
  readonly name: string;
  readonly model: string;
  readonly isDemo = false;
  private baseUrl: string;
  private apiKey: string;

  constructor(name: Exclude<ProviderName, 'demo'>, apiKey: string) {
    const preset = PRESETS[name];
    this.name = name;
    this.baseUrl = (process.env.OPENAI_BASE_URL && name === 'custom' ? process.env.OPENAI_BASE_URL : preset.baseUrl).replace(/\/$/, '');
    this.model = process.env.OPENAI_CHAT_MODEL || preset.model;
    this.apiKey = apiKey;
  }

  async chat(messages: LLMMessage[], options?: { temperature?: number; maxTokens?: number }): Promise<LLMChatResult> {
    const res = await fetch(`${this.baseUrl}/chat/completions`, {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        authorization: `Bearer ${this.apiKey}`,
      },
      body: JSON.stringify({
        model: this.model,
        messages,
        temperature: options?.temperature ?? 0.3,
        max_tokens: options?.maxTokens ?? 900,
      }),
      signal: AbortSignal.timeout(45_000),
    });
    if (!res.ok) {
      const body = await res.text().catch(() => '');
      throw new Error(`LLM provider error ${res.status}: ${body.slice(0, 300)}`);
    }
    const json = (await res.json()) as { choices?: Array<{ message?: { content?: string } }> };
    const text = json.choices?.[0]?.message?.content?.trim();
    if (!text) throw new Error('LLM provider returned an empty response');
    return { text, provider: this.name, model: this.model };
  }

  async embed(texts: string[]): Promise<number[][]> {
    const model = process.env.OPENAI_EMBEDDING_MODEL || 'text-embedding-3-small';
    const res = await fetch(`${this.baseUrl}/embeddings`, {
      method: 'POST',
      headers: { 'content-type': 'application/json', authorization: `Bearer ${this.apiKey}` },
      body: JSON.stringify({ model, input: texts }),
      signal: AbortSignal.timeout(30_000),
    });
    if (!res.ok) throw new Error(`Embedding provider error ${res.status}`);
    const json = (await res.json()) as { data?: Array<{ embedding: number[] }> };
    return (json.data ?? []).map((d) => d.embedding);
  }
}

/**
 * Offline demo provider — clearly labelled everywhere in the UI.
 * Conversational answers in demo mode are generated by the rule-based
 * grounded generator in `prompts.ts` (retrieval + templates), not here.
 */
class DemoProvider implements LLMProvider {
  readonly name = 'demo';
  readonly model = 'pathalign-rule-based-v1';
  readonly isDemo = true;

  async chat(messages: LLMMessage[]): Promise<LLMChatResult> {
    const lastUser = [...messages].reverse().find((m) => m.role === 'user');
    const text =
      lastUser?.content.trim().slice(0, 400) ??
      'Configure AI_PROVIDER with an API key for LLM responses.';
    return { text, provider: this.name, model: this.model };
  }
}

let cached: LLMProvider | null = null;

export function getProvider(): LLMProvider {
  if (cached) return cached;
  const name = (process.env.AI_PROVIDER || 'demo') as ProviderName;
  const key = process.env.OPENAI_API_KEY || '';
  if (name !== 'demo' && key) {
    cached = new OpenAICompatibleProvider(name, key);
  } else {
    cached = new DemoProvider();
  }
  return cached;
}

export function resetProviderCache(): void {
  cached = null;
}

export function aiStatus(): { provider: string; model: string; mode: 'demo' | 'llm'; ragMode: string } {
  const p = getProvider();
  return {
    provider: p.name,
    model: p.model,
    mode: p.isDemo ? 'demo' : 'llm',
    ragMode: vectorSafe() ? 'vector' : 'lexical',
  };
}

function vectorSafe(): boolean {
  return process.env.ENABLE_VECTOR_SEARCH === 'true' && Boolean(process.env.OPENAI_API_KEY);
}
